server:
  port: 9090

security:
  jwt:
    client-secret: XY7kmzoNzl100
    token-validity-seconds: 6060


spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/skillsbase
    username: skillsbase
    password: skillsbase

